# Generated by Django 4.2.2 on 2023-06-29 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuários',
            new_name='Usuario',
        ),
    ]
